### ISSUE TITLE
Ignore undercover messages sent to bot 

### ISSUE THREAD

**Issue by GoelBiju** [nortxort/tinybot#3]
@Autotonic mentioned this a while ago saying how it would be easy for commands to be started by sending the client an undercover message. We need to make sure the bot does not handle any undercover messages that are sent. 

I am just confused as to how to recognise the difference between a normal chat message and undercover message.

**Comment by nortxort** [comment]
".. it would be easy for commands to be started by sending the client an undercover message" How??
Since a "undercover" is a privmsg with the only difference being, that the user name and id of the receiver is sent along with it (and the color being #0). The message still has to go thru on_privmsg where the user sender will be looked up in the user class and get assigned to the variable self.active_user now as a user object before the message is sent along to message_handler. Once the message reaches message_handler, self.has_level takes over. So i really don't see how it would be possible, but do correct me if i am wrong.

**Comment by GoelBiju** [comment]
@nortxort , sorry I didn't explain it properly. I was saying that it is possible for the commands to be started but all the same privileges still apply, so there is nothing wrong with using the commands, the only issue is that the message will not be seen in the actual chat and at times this might seem odd. E.g. sending a youtube/soundcloud command, the video/track would be added, however who sent it is not visible for others without checking the console.

**Comment by nortxort** [comment]
@GoelBiju I made a few changes to pinylib https://github.com/nortxort/pinylib/commit/936a59279c5de0c533d54f469493941a1396ea09 This should prevent the issue from happening.

**Comment by Autotonic** [comment]
@nortxort https://github.com/nortxort/pinylib/commit/936a59279c5de0c533d54f469493941a1396ea09#diff-78ebb9159d0f2e62a68dd98ab604723eR646
is a quick but dirty fix for it as many users still using the old swf or tc_client

**Comment by nortxort** [comment]
@Autotonic Whether or not you find it a dirty fix or not isn't very helpful and also rather of topic. I could have done this in a few ways:

```
        else:
            # allowing old colors to.
            if len(msg_color) is 10:
                self.message_handler(decoded_msg.strip())
```
 or 

```
        else:
            # rejecting only official undercover messages.
            if msg_color != u'#0,en':
                self.message_handler(decoded_msg.strip())
```
I posted a solution based on the info GoelBiju had provided me with. If you don't find any of the posted solutions  up to your coding standards, the feel free to post your own solution.

**Comment by Autotonic** [comment]
Was more so for others to understand to effect that it could have as far as ignoring clients who use color. My "coding standards" further the off-topic remark.

**Comment by nortxort** [comment]
Changed to support old style colors to.
